In [1]:
import pandas as pd
import io, os, sys, types
from IPython import get_ipython
from IPython.display import display, Javascript, HTML
import json
import pandas as pd 
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import datetime
# from scipy.stats import sem
import os
import pylab 
import scipy.stats as stats
import matplotlib as mpl

plt.style.use('ggplot')
%matplotlib inline
# import DataProcessor as dp

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

In [2]:
#reading in the csv and visualizing the head
df_suicide_rates_data = pd.read_csv("./Data/Suicide_Rates_Data.csv")

df_suicide_rates_data.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

In [3]:
#dropping useless column that will not be used
df_suicide_rates_data_new = df_suicide_rates_data
df_suicide_rates_data_new.drop(['HDI for year'], axis=1)

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,"2,156,624,900",796,Boomers
5,Albania,1987,female,75+ years,1,35600,2.81,Albania1987,"2,156,624,900",796,G.I. Generation
6,Albania,1987,female,35-54 years,6,278800,2.15,Albania1987,"2,156,624,900",796,Silent
7,Albania,1987,female,25-34 years,4,257200,1.56,Albania1987,"2,156,624,900",796,Boomers
8,Albania,1987,male,55-74 years,1,137500,0.73,Albania1987,"2,156,624,900",796,G.I. Generation
9,Albania,1987,female,5-14 years,0,311000,0.00,Albania1987,"2,156,624,900",796,Generation X
10,Albania,1987,female,55-74 years,0,144600,0.00,Albania1987,"2,156,624,900",796,G.I. Generation
11,Albania,1987,male,5-14 years,0,338200,0.00,Albania1987,"2,156,624,900",796,Generation X
12,Albania,1988,female,75+ years,2,36400,5.49,Albania1988,"2,126,000,000",769,G.I. Generation
13,Albania,1988,male,15-24 years,17,319200,5.33,Albania1988,"2,126,000,000",769,Generation X
14,Albania,1988,male,75+ years,1,22300,4.48,Albania1988,"2,126,000,000",769,G.I. Generation
15,Albania,1988,male,35-54 years,14,314100,4.46,Albania1988,"2,126,000,000",769,Silent
16,Albania,1988,male,55-74 years,4,140200,2.85,Albania1988,"2,126,000,000",769,G.I. Generation
17,Albania,1988,female,15-24 years,8,295600,2.71,Albania1988,"2,126,000,000",769,Generation X
18,Albania,1988,female,55-74 years,3,147500,2.03,Albania1988,"2,126,000,000",769,G.I. Generation
19,Albania,1988,female,25-34 years,5,262400,1.91,Albania1988,"2,126,000,000",769,Boomers
20,Albania,1988,male,25-34 years,5,279900,1.79,Albania1988,"2,126,000,000",769,Boomers
21,Albania,1988,female,35-54 years,4,284500,1.41,Albania1988,"2,126,000,000",769,Silent
22,Albania,1988,female,5-14 years,0,317200,0.00,Albania1988,"2,126,000,000",769,Generation X
23,Albania,1988,male,5-14 years,0,345000,0.00,Albania1988,"2,126,000,000",769,Generation X
24,Albania,1989,male,75+ years,2,22500,8.89,Albania1989,"2,335,124,988",833,G.I. Generation
25,Albania,1989,male,25-34 years,18,283600,6.35,Albania1989,"2,335,124,988",833,Boomers
26,Albania,1989,male,35-54 years,15,318400,4.71,Albania1989,"2,335,124,988",833,Silent
27,Albania,1989,male,55-74 years,6,142100,4.22,Albania1989,"2,335,124,988",833,G.I. Generation
28,Albania,1989,male,15-24 years,12,323500,3.71,Albania1989,"2,335,124,988",833,Generation X
29,Albania,1989,female,35-54 years,7,288600,2.43,Albania1989,"2,335,124,988",833,Silent
...,...,...,...,...,...,...,...,...,...,...,...
27790,Uzbekistan,2012,female,25-34 years,148,2556673,5.79,Uzbekistan2012,"51,821,573,338",1964,Millenials
27791,Uzbekistan,2012,female,35-54 years,89,3474788,2.56,Uzbekistan2012,"51,821,573,338",1964,Generation X
27792,Uzbekistan,2012,male,5-14 years,67,2701361,2.48,Uzbekistan2012,"51,821,573,338",1964,Generation Z
27793,Uzbekistan,2012,female,55-74 years,25,1283060,1.95,Uzbekistan2012,"51,821,573,338",1964,Boomers
27794,Uzbekistan,2012,female,75+ years,4,338557,1.18,Uzbekistan2012,"51,821,573,338",1964,Silent
27795,Uzbekistan,2012,female,5-14 years,16,2578408,0.62,Uzbekistan2012,"51,821,573,338",1964,Generation Z
27796,Uzbekistan,2013,male,35-54 years,481,3346411,14.37,Uzbekistan2013,"57,690,453,461",2150,Generation X
27797,Uzbekistan,2013,male,25-34 years,328,2644648,12.40,Uzbekistan2013,"57,690,453,461",2150,Millenials
27798,Uzbekistan,2013,female,15-24 years,323,3039740,10.63,Uzbekistan2013,"57,690,453,461",2150,Millenials
27799,Uzbekistan,2013,male,15-24 years,320,3171202,10.09,Uzbekistan2013,"57,690,453,461",2150,Millenials
27800,Uzbekistan,2013,male,55-74 years,119,1202790,9.89,Uzbekistan2013,"57,690,453,461",2150,Boomers
27801,Uzbekistan,2013,male,75+ years,13,221002,5.88,Uzbekistan2013,"57,690,453,461",2150,Silent
27802,Uzbekistan,2013,female,25-34 years,146,2647820,5.51,Uzbekistan2013,"57,690,453,461",2150,Millenials
27803,Uzbekistan,2013,female,35-54 years,99,3547895,2.79,Uzbekistan2013,"57,690,453,461",2150,Generation X
27804,Uzbekistan,2013,female,75+ years,8,345180,2.32,Uzbekistan2013,"57,690,453,461",2150,Silent
27805,Uzbekistan,2013,male,5-14 years,61,2720938,2.24,Uzbekistan2013,"57,690,453,461",2150,Generation Z
27806,Uzbekistan,2013,female,55-74 years,21,1356298,1.55,Uzbekistan2013,"57,690,453,461",2150,Boomers
27807,Uzbekistan,2013,female,5-14 years,31,2595000,1.19,Uzbekistan2013,"57,690,453,461",2150,Generation Z
27808,Uzbekistan,2014,male,35-54 years,519,3421300,15.17,Uzbekistan2014,"63,067,077,179",2309,Generation X
27809,Uzbekistan,2014,male,25-34 years,318,2739150,11.61,Uzbekistan2014,"63,067,077,179",2309,Millenials
27810,Uzbekistan,2014,female,15-24 years,347,2992817,11.59,Uzbekistan2014,"63,067,077,179",2309,Millenials
27811,Uzbekistan,2014,male,55-74 years,144,1271111,11.33,Uzbekistan2014,"63,067,077,179",2309,Boomers
27812,Uzbekistan,2014,male,15-24 years,347,3126905,11.10,Uzbekistan2014,"63,067,077,179",2309,Millenials
27813,Uzbekistan,2014,male,75+ years,17,224995,7.56,Uzbekistan2014,"63,067,077,179",2309,Silent
27814,Uzbekistan,2014,female,25-34 years,162,2735238,5.92,Uzbekistan2014,"63,067,077,179",2309,Millenials
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,"63,067,077,179",2309,Boomers

In [4]:
preview_df_year=df_suicide_rates_data_new[['year']]
preview_df_year.sort_values(by='year',ascending=False).head()

       year
17442  2016
16937  2016
2162   2016
2163   2016
2164   2016

In [5]:
pd.date_range(start='2011', end='2016')

DatetimeIndex(['2011-01-01', '2011-01-02', '2011-01-03', '2011-01-04',
               '2011-01-05', '2011-01-06', '2011-01-07', '2011-01-08',
               '2011-01-09', '2011-01-10',
               ...
               '2015-12-23', '2015-12-24', '2015-12-25', '2015-12-26',
               '2015-12-27', '2015-12-28', '2015-12-29', '2015-12-30',
               '2015-12-31', '2016-01-01'],
              dtype='datetime64[ns]', length=1827, freq='D')

In [6]:
preview_df_gen=df_suicide_rates_data_new[['year','generation']]
preview_df_gen.sort_values(by='generation',ascending=False)

       year generation
22044  2004     Silent
21858  2009     Silent
8499   2007     Silent
8503   2007     Silent
8504   2007     Silent
21859  2009     Silent
8510   2008     Silent
8511   2008     Silent
8515   2008     Silent
8492   2006     Silent
8516   2008     Silent
21854  2009     Silent
8522   2009     Silent
21853  2009     Silent
8524   2009     Silent
8527   2009     Silent
8498   2007     Silent
8489   2006     Silent
8534   2010     Silent
21870  2010     Silent
8457   2003     Silent
8462   2004     Silent
8464   2004     Silent
8467   2004     Silent
8468   2004     Silent
21871  2010     Silent
8475   2005     Silent
21866  2010     Silent
8476   2005     Silent
8479   2005     Silent
...     ...        ...
8900   2000    Boomers
21591  2011    Boomers
21657  1987    Boomers
21663  1987    Boomers
8781   1990    Boomers
8827   1994    Boomers
21718  1998    Boomers
21709  1997    Boomers
8787   1991    Boomers
8788   1991    Boomers
21705  1997    Boomers
8791   1991    Boomers
8794   1991    Boomers
8798   1992    Boomers
8799   1992    Boomers
21694  1996    Boomers
21693  1996    Boomers
8803   1992    Boomers
8805   1992    Boomers
21686  1995    Boomers
8810   1993    Boomers
8812   1993    Boomers
8815   1993    Boomers
21680  1995    Boomers
8817   1993    Boomers
8822   1994    Boomers
21672  1990    Boomers
8824   1994    Boomers
21668  1990    Boomers
27819  2014    Boomers

[27820 rows x 2 columns]

In [7]:
preview_df_all=df_suicide_rates_data_new[['generation','suicides_no', 'age', 'year', 'gdp_per_capita ($)']]
preview_df_all.sort_values(by='suicides_no',ascending=False).head()

      generation  suicides_no          age  year  gdp_per_capita ($)
20996    Boomers        22338  35-54 years  1994                2853
21008    Boomers        21706  35-54 years  1995                2844
21080    Boomers        21262  35-54 years  2001                2229
21068    Boomers        21063  35-54 years  2000                1879
21057    Boomers        20705  35-54 years  1999                1412

In [8]:
gen_gdp_data = df_suicide_rates_data_new.groupby(['year', 'generation', 'gdp_per_capita ($)'])['suicides_no'].sum()
#suicides_no = generation['generation'].sum()
print(gen_gdp_data)

year  generation  gdp_per_capita ($)
1985  Boomers     431                   1450
                  840                    707
                  964                     10
                  1032                     1
                  1223                    25
                  1393                   238
                  1485                     0
                  1622                     0
                  1658                   141
                  1729                    33
                  1898                  1060
                  1965                     0
                  2044                   141
                  2145                    35
                  2238                   101
                  2706                    11
                  2730                   401
                  2731                   883
                  2912                   118
                  2947                     0
                  3264                   242
                  3443                    18
                  3639                     0
                  3850                     0
                  5009                   278
                  5156                    58
                  6137                     3
                  6582                    51
                  6638                    58
                  7317                    10
                                        ...
2016  Millenials  6713                  1144
                  10020                  266
                  10570                   42
                  10838                    0
                  12905                   90
                  13448                  200
                  15742                  151
                  19505                  271
                  25098                    8
                  46976                  184
                  48108                  336
                  55594                  264
                  62484                   36
                  64708                   16
      Silent      3788                    14
                  4145                     6
                  6713                   221
                  10020                  232
                  10570                    3
                  10838                    0
                  12905                  144
                  13448                  334
                  15742                  107
                  19505                  165
                  25098                    2
                  46976                  273
                  48108                  210
                  55594                  145
                  62484                    0
                  64708                    1
Name: suicides_no, Length: 10663, dtype: int64

In [9]:
gen_year_data = df_suicide_rates_data_new.groupby(['year', 'generation'])['suicides_no'].sum()
#suicides_no = generation['generation'].sum()
print(gen_year_data)

year  generation
1985  Boomers             20771
      G.I. Generation     40690
      Generation X        18854
      Silent              35748
1986  Boomers             21685
      G.I. Generation     42420
      Generation X        19007
      Silent              37558
1987  Boomers             22309
      G.I. Generation     46517
      Generation X        17367
      Silent              40649
1988  Boomers             21332
      G.I. Generation     44750
      Generation X        16174
      Silent              38770
1989  Boomers             29427
      G.I. Generation     57490
      Generation X        19786
      Silent              53541
1990  Boomers             35276
      G.I. Generation     68118
      Generation X        24725
      Silent              65242
1991  Boomers            103989
      G.I. Generation     20866
      Generation X        23317
      Millenials           1533
      Silent              48315
1992  Boomers            112809
                          ...
2010  Silent              83577
2011  Boomers             59178
      Generation X        85345
      Generation Z         1879
      Millenials          65873
      Silent              24209
2012  Boomers             58443
      Generation X        82482
      Generation Z         1752
      Millenials          62905
      Silent              24578
2013  Boomers             57696
      Generation X        80227
      Generation Z         1806
      Millenials          59317
      Silent              24153
2014  Boomers             57696
      Generation X        79132
      Generation Z         1882
      Millenials          59409
      Silent              24865
2015  Boomers             53588
      Generation X        71298
      Generation Z         1681
      Millenials          53959
      Silent              23114
2016  Boomers              4715
      Generation X         5766
      Millenials           3265
      Silent               1857
Name: suicides_no, Length: 146, dtype: int64

In [10]:
gen_freq_data = df_suicide_rates_data_new.groupby(['generation']) ['suicides_no'].count()

print(gen_freq_data)

generation
Boomers            4990
G.I. Generation    2744
Generation X       6408
Generation Z       1470
Millenials         5844
Silent             6364
Name: suicides_no, dtype: int64

In [11]:
df_suicide_stats = df_suicide_rates_data_new[['generation', 'year', 'suicides_no', 'gdp_per_capita ($)']]
print(df_suicide_stats)

            generation  year  suicides_no  gdp_per_capita ($)
0         Generation X  1987           21                 796
1               Silent  1987           16                 796
2         Generation X  1987           14                 796
3      G.I. Generation  1987            1                 796
4              Boomers  1987            9                 796
5      G.I. Generation  1987            1                 796
6               Silent  1987            6                 796
7              Boomers  1987            4                 796
8      G.I. Generation  1987            1                 796
9         Generation X  1987            0                 796
10     G.I. Generation  1987            0                 796
11        Generation X  1987            0                 796
12     G.I. Generation  1988            2                 769
13        Generation X  1988           17                 769
14     G.I. Generation  1988            1                 769
15              Silent  1988           14                 769
16     G.I. Generation  1988            4                 769
17        Generation X  1988            8                 769
18     G.I. Generation  1988            3                 769
19             Boomers  1988            5                 769
20             Boomers  1988            5                 769
21              Silent  1988            4                 769
22        Generation X  1988            0                 769
23        Generation X  1988            0                 769
24     G.I. Generation  1989            2                 833
25             Boomers  1989           18                 833
26              Silent  1989           15                 833
27     G.I. Generation  1989            6                 833
28        Generation X  1989           12                 833
29              Silent  1989            7                 833
...                ...   ...          ...                 ...
27790       Millenials  2012          148                1964
27791     Generation X  2012           89                1964
27792     Generation Z  2012           67                1964
27793          Boomers  2012           25                1964
27794           Silent  2012            4                1964
27795     Generation Z  2012           16                1964
27796     Generation X  2013          481                2150
27797       Millenials  2013          328                2150
27798       Millenials  2013          323                2150
27799       Millenials  2013          320                2150
27800          Boomers  2013          119                2150
27801           Silent  2013           13                2150
27802       Millenials  2013          146                2150
27803     Generation X  2013           99                2150
27804           Silent  2013            8                2150
27805     Generation Z  2013           61                2150
27806          Boomers  2013           21                2150
27807     Generation Z  2013           31                2150
27808     Generation X  2014          519                2309
27809       Millenials  2014          318                2309
27810       Millenials  2014          347                2309
27811          Boomers  2014          144                2309
27812       Millenials  2014          347                2309
27813           Silent  2014           17                2309
27814       Millenials  2014          162                2309
27815     Generation X  2014          107                2309
27816           Silent  2014            9                2309
27817     Generation Z  2014           60                2309
27818     Generation Z  2014           44                2309
27819          Boomers  2014           21                2309

[27820 rows x 4 columns]

In [12]:
df_suicide_stats.corr(method ='pearson')

                        year  suicides_no  gdp_per_capita ($)
year                1.000000    -0.004546            0.339134
suicides_no        -0.004546     1.000000            0.061330
gdp_per_capita ($)  0.339134     0.061330            1.000000

In [16]:
df_suicide_stats.groupby('year')